version: '3'

services:
  redis:
    image: redis
    command: redis-server 
    ports:
      - "6379:6379"

  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        DEFAULT_IP_LIMIT: 10
        DEFAULT_TOKEN_LIMIT: 100
        BLOCK_DURATION: 300
      depends_on:
        - redis